[modules]
autoload = yes

load = res_ari.so
load = res_ari_applications.so
load = res_ari_asterisk.so
load = res_ari_bridges.so
load = res_ari_channels.so
load = res_ari_endpoints.so
load = res_ari_events.so
load = res_http_websocket.so
load = res_pjsip.so
load = chan_pjsip.so
load = app_stasis.so
load = app_dial.so
load = app_stack.so

noload = chan_sip.so
