---
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded
    enabled: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
